services:
  ma-bao-guo-backend:
    image: ma-bao-guo-backend:1.0
    ports:
      - "8081:8081"
    depends_on:
      counchdb:
        condition: service_started
    networks:
      - couchserver_network
      
  ma-bao-guo-dashboard:
    image: ma-bao-guo-dashboard:1.0
    ports:
      - "8080:8080"
    depends_on:
      ma-bao-guo-backend:
        condition: service_started        
      
  counchdb:
    image: bitnami/couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    volumes:
      - couchdb_data:/bitnami/couchdb
    networks:
      - couchserver_network  
      
volumes:
  couchdb_data:
    driver: local
    
networks:
  couchserver_network:
    driver: bridge       
